h2oai/cloud-discovery-py

README.md, src/h2o_discovery/__init__.py, src/h2o_discovery/async_client.py, src/h2o_discovery/client.py, src/h2o_discovery/discovery.py, tests/e2e/test_clients.py, tests/e2e/test_environment.py, tests/e2e/test_services.py, tests/test_async_client.py, tests/test_discovery.py
BREAKING CHANGE: Rename default netrypoint function to `discover_async`.
Voting on https://github.com/h2oai/cloud-discovery/issues/127 decided to have default `discover` as synchronous option.
All of the internal methods and tests are renamed to contain `_async` if there's a chance they get sycnhronous variant. Some pieces of the code are adjusted to allow reuse with synchrnous varaint.
PART OF https://github.com/h2oai/cloud-discovery/issues/127
=> refactor: Prepare code for inclusion for sycnhrnous entry point

src/h2o_discovery/model.py, tests/test_client.py, tests/test_discovery.py, tests/test_model.py
added field is `Optional` to be compatible with the version of the BE that does not have it.
PART OF https://github.com/h2oai/cloud-discovery/issues/159
FOLLOW UP FOR https://github.com/h2oai/cloud-discovery/pull/160
=> feat: add support for `version` field in the environment

.github/workflows/python-build.yml, .github/workflows/python-lint.yml, .github/workflows/python-test.yml, .github/workflows/python.yml
- run all of the jobs in the main Python wokflow as reusable workflows
- add aggregate job for both build and test workflows so that we can see the status of the whole workflow in the PR checks
=> ci: 👷 extract all jobs to reusable worklows

pydoc-markdown.yml, pyproject.toml
This will be used for generating reference docs for releases.
PART OF #h2oai/cloud-discovery#170
=> chore: 🔧 Configure pydoc-markdown doc generator

.github/ISSUE_TEMPLATE/type_bug.md, .github/ISSUE_TEMPLATE/type_improvement.md, .github/ISSUE_TEMPLATE/type_new_feature.md, .github/ISSUE_TEMPLATE/type_task.md
**Requirement**
- There is a requirement by Michal on mandatory rules and settings that should be configured in GH repos to cater to the SOC2 compliance requirements. #366
- The document below covers an overview of the suggested and recommended Github Repository Baseline Settings;
- https://h2oai.atlassian.net/wiki/spaces/DEVOPS/pages/3921739777/GitHub+Repository+Baseline+Settings
- [Software Development-1.pdf](https://github.com/h2oai/admin-analytics-wave-app/files/11722423/Software.Development-1.pdf)
**Changed list**
- ISSUE_TEMPLATE file added
- Added branch rules and added synk for status check.
- Admin access to the repo restricted except for special cases and it should be approved by the Ops leadership if needed (Jeff/MichalM).
**Kindly please validate to merge to the main branch**
=> added ISSUE_template file and enforced Branch Rules

.github/workflows/snyk-monitor.yaml, .github/workflows/snyk-test.yaml
- skip test for dependabot PRs
- dependabot does not have access to SNYK_TOKEN
- add `--fail-on=all ` so that test does not fail on issues that cannot be fixed
- add schedule for the monitor so that issues caused by transient dependencies can fix themselves automaticaly as we do no lock verisons being a library
- remove whitespaces
- format using GHA formatter (unifies quote signs)
=> ci: 👷 update snyk workflows

tests/_internal/lookup/test_determine_uri.py
`_find_` in the test name was reference to the original version for the fuction.
Also move test file to the own dir as a preparation for adding another test suit for https://github.com/h2oai/cloud-discovery/issues/267
=> refactor: ♻️ rename lookup tests to reflect the function name

README.md, pyproject.toml
Current `test` environment has matrix for `httpx` and `python` versions and tests against packaged version of the project to verify the build result.
This is overkill for local cevelopment sanity checks. Hatch does not update the project when there are changes to the sources so `dev-mode = false` `hatch env remove` is neeede with `test` ro verify changes.
=> chore: 🧑‍💻 add `devtest` environment for quick development tests

src/h2o_discovery/__init__.py, src/h2o_discovery/_internal/load.py, src/h2o_discovery/exceptions.py
As this is second specific exception raised from the main functions, we adopt custom exceptions pattern.
`load` functions now check some specific errors that can hint that the environment does not have discovery service installed.
RESOLVES #23
=> feat: 🥅 handle errors that hint discovery server not being enabled in environment.

pyproject.toml
before this change, everything, including the `.github` directory is part of the `tar.gz` being uploaded to pypi.
=> chore: 🔧 limit what files are part of `sdist`

pyproject.toml, src/h2o_discovery/__init__.py, src/h2o_discovery/_internal/compat.py, src/h2o_discovery/_internal/config.py, src/h2o_discovery/_internal/load.py, src/h2o_discovery/_internal/lookup.py, tests/_internal/load/test_load_credentials.py, tests/_internal/lookup/test_determine_local_config_path.py, tests/_internal/test_config.py
- implement config path lookup
- implement config loading
- extend credentials loading to accept tokens loaded from the config
- extend main discover functions to accept config path and utilize
RESOLVES https://github.com/h2oai/cloud-discovery/issues/437
=> feat: ✨ add support for reading client credentials from the local H2O CLI config file

src/h2o_discovery/__init__.py, src/h2o_discovery/_internal/config.py, src/h2o_discovery/_internal/lookup.py, tests/_internal/lookup/test_determine_uri.py, tests/_internal/test_config.py
`determine_uri` now accepts `config_endpoint` as the existence of `H2OCONFIG` is not in the concernt of it, we moved the verbose `LookupError` to the main functrions.
RESOLVES https://github.com/h2oai/cloud-discovery/issues/438
=> feat: ✨ add support for reading endpoint from the local H2O CLI configuration file

pyproject.toml
This fixes error on the CI (https://github.com/h2oai/cloud-discovery-py/actions/runs/6219626115/job/16878063334)
API doc was for the release was updated manually.
=> chore: 💚 update `pydoc-markdown`

pyproject.toml, src/h2o_discovery/_internal/lookup.py
[`ruff format` is available from `0.1.2`](https://docs.astral.sh/ruff/formatter/) using instead of `black`:
- removes one dependency/tool
- improves speed of the linting.
one trailing comma added by the formatter.
=> chore: 🔨 use `ruff format` instead of `black` for formatting

.github/workflows/release-please.yml
Currently the release workflow executes with any commit to default branch. It fails as the upload to the PyPI fails on uniqueness constraint.
- fix condition so that it's evaluated as bool.
- set job output tag.
=> ci: 💚 fix release please work flow

.github/workflows/pypi-release.yml, .github/workflows/python-build.yml, .github/workflows/python-test.yml, pyproject.toml
BREAKING CHANGE: Python 3.7 is no longer supported. The minimum supported version is now Python 3.8.
- Remove official support for Python 3.7 from the package metadata.
- Remove Python 3.7 from the CI matrix.
=> build!: 💥 remove support for Python 3.7

.github/workflows/release-please.yml
It stopped working on https://github.com/h2oai/authn-py and with draft releases finaly working in the action it's not so much.
=> ci: 💚 remove dependency on the ops account for release please jobs

.github/workflows/pypi-release.yml, .github/workflows/release-please.yml
This repo should be authorized as the trusted publisher.
Also adjusted config keys to preferred `kebab-case`.
TOKEN itself will be removed once we confirm that this works.
=> ci: 👷 drop use of the token for PyPI release

src/h2o_discovery/__init__.py, src/h2o_discovery/_internal/client.py
It turned out that the support was already done on the lower level but never exposed on the entry functions level.
fix: use inherited constructor in sync `Client`
feat: use default ssl context by default
RESOLVES #100
=> feat: ✨ expose http timeout and ssl context options on the entry functions

src/h2o_discovery/_internal/client.py
Use the prepared client factory with all of the options passed instead of direct call to httpx.
I have no explanation why it was the way it was.
RESOLVES #104
=> fix: 🐛 pass the timeout and ssl_context to the httpx

.github/workflows/pypi-release.yml
They do no seem to work with reusable workflows (see the issues in the comment)
=> ci: 💚 disable pypi attestations production and upload

pyproject.toml
This is to avoid deprecation warnings with higher python versions.
`pytest-asyncio==0.24.0` is the latest version that supports Python 3.8.
=> chore: Bump pytest and pytest-asyncio version

.github/workflows/python-build.yml, .github/workflows/python-lint.yml, .github/workflows/python-test.yml, pyproject.toml, tests/_internal/load/test_load_discovery.py
[Python 3.13 removed cgi module](https://docs.python.org/3.13/library/cgi.html), which is used by httpx 0.22 and lower.
So we do not test with lower version with Python 3.13 and set higher requirements for Python 3.13+
Tests were producing deprecation warning on the places when we assign futures to mock so I rewrote initialization of the mocks.
`pytest-asyncio` produces deprecation warnings with Python 3.14, so I added python version constraints to the test dependencies and use the newest `pytest-asyncio` for python 3.9+
Newer versions of httpx are added to testing matrix.
=> test: ✅ Extend testing in Python 3.13+ 

src/h2o_discovery/_internal/client.py, src/h2o_discovery/model.py, tests/_internal/test_client.py, tests/test_model.py
- defines the model for the link entity
- add methods for fetching links from the server
PART OF https://github.com/h2oai/cloud-discovery/issues/694
=> refactor: 🚧 Add support for link entity to client

src/h2o_discovery/_internal/load.py, src/h2o_discovery/model.py, tests/_internal/load/test_load_discovery.py
- add links map to the discovery model
- load links when the discover is called
As Links are new addtion to the API, we do not fail when server returns 404 and only have no links available. All this to have backward compatibility.
RESOLVES https://github.com/h2oai/cloud-discovery/issues/694
=> feat: ✨ Discover registered links when available

src/h2o_discovery/model.py, tests/_internal/test_client.py, tests/test_model.py
`h2o_discovert.model` uses `dataclasses` module and let it generate `__init__` method.
We do not set any default value for any `Optional` field, so the generated `__init__` method
looks like this:
```py
def __init__(self, field1: Optional[str], field2: Optional[str], field3: Optional[str]):
```
That makes all fileds required args in the constructor.
Adding links therefore added new required `links` argument to the
`h2o_discovert.model.Discovery` constructor.
We set the default value for `links` field of the `Discovery` class
and to all Optional fields of other classes as well to establish the pattern.
=> fix: 🐛 Make addition of links to the discovery model backward compatible

src/h2o_discovery/_internal/load.py
Discovery requires multiple requests to get all of the data. Asyncio allows us to send all requets concurently and the await the results.
This should improve latency of the async variant
=> perf: ⚡️ Fetch data concurrently in async mode

pyproject.toml
`httpcore` that is dependency of the `httpx` causes `AttributeError` for `httpcore<1.0.8`.
(https://github.com/encode/httpcore/blob/master/CHANGELOG.md#version-108-april-11th-2025)
Support for `httpcore>=1.0` was added in `httpc==0.25.1`.
(https://github.com/encode/httpx/blob/master/CHANGELOG.md#0251-3rd-november-2023)
Constraining  httpx for python 3.14  allows to use resolve httpx to versions can use `httpcore` that fixes the issue for python 3.14
=> feat: improve compatibility with Python 3.14

pyproject.toml, src/h2o_discovery/__init__.py, src/h2o_discovery/_internal/load.py, tests/_internal/load/test_load_credentials.py
This can happen when the discovery endpoint is set explicitly or via env variables.
Such credentials do not work with the target environment anyway.
=> fix: 🐛 don't load credentials when config does not match the discovered environment

pyproject.toml
hatch has support for uv https://hatch.pypa.io/dev/how-to/environment/select-installer/
```sh
hatch env remove devtest && hatch run devtest:pytest
```
Takes our ~4s on my machine without uv. With uv its ~1s.
=> build: 👷 set `uv` as installer for hatch
